---
ovirt_url: "https://ovirt.pst.rockplace.co.kr/ovirt-engine/api" # {{ lookup('env', 'OVIRT_URL') }}
ovirt_username: {{ lookup('env', 'OVIRT_USERNAME') }}
ovirt_password: {{ lookup('env', 'OVIRT_PASSWORD') }}

vm_prefix: "mwsong-test-"
vm_auth_key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}" ## "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3KhYWwE3F2OxiLplD1fqD0XpeEfEpZoJy8WEmi7RakAsDWPXBVrpwcXhIlaDm4VQCIGCUqxfEKR5jePz9yD7XM9okfXtHcwbkMBfhfO2oVEhs/e/P6EzuY8lHeUk5T/FqCCCGWCA8ktXQbOrzQ3qJion5ppQZqSV0fpuZv4cwf98jbMIFcMfbUNHGXFnsJWW0/7/vrQRa4Q4pDgEMIbxD2GNUg7iuvKGt4h7qNCvbw5Nk8SwmCR+Rw2yGG8BVQaZbSGhjCiU9Y0v08r0HaxCOLLt0aAOCaPXmsMGQAfiy5KEY+qUG/hzTho460o84RVkztDtpr30x4wvRyACwc9A5"

# deprecated
vms:
  - name: "bastion"
    ipaddress: "10.65.40.10"
    hostname: "bastion.mwk8s.com"
  - name: "bootstrap"
    ipaddress: "10.65.40.11"
    hostname: "bootstrap.mwk8s.com"
  - name: "master-01"
    ipaddress: "10.65.40.12"
    hostname: "master-01.mwk8s.com"
  - name: "worker-01"
    ipaddress: "10.65.40.13"
    hostname: "worker-01.mwk8s.com"
  - name: "route-01"
    ipaddress: "10.65.40.14"
    hostname: "route-01.mwk8s.com"

